name: Active releases

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore CommonShop.WebApiGateway.csproj
      - name: Publish
        run: dotnet publish --configuration Release --no-restore CommonShop.WebApiGateway.csproj
      - name: Build docker image
        run: docker build --tag weisong0908/common-shop-webapi-gateway .
      - name: Login to Docker Hub with access token
        run: docker login -u weisong0908 -p ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - name: Push docker image to Docker Hub
        run: docker push weisong0908/common-shop-webapi-gateway
  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executes remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVERADDRESS }}
          username: weisong0908
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          port: 22
          script: |
            docker stop webapi-gateway
            docker pull weisong0908/common-shop-webapi-gateway
            docker run -d --rm -p 5000:80 --name webapi-gateway -e ASPNETCORE_ENVIRONMENT=Staging weisong0908/common-shop-webapi-gateway
